### ISSUE TITLE
Return is coming empty 

### ISSUE THREAD

**Issue by Mr-Frey** [MrWildanMD/MemDumper#1]
I am passing the name and PID of the application, but it is returning empty.
![Screenshot_20231206-185315-1.png](https://github.com/MrWildanMD/MemDumper/assets/116834722/460bfc0b-6289-49c6-99c2-79976c4632cb)

Can you help me?

**Comment by MrWildanMD** [comment]
Alright, first thing you need to make sure:
1. Is the process have the lib called libil2cpp.so?
2. You can try using process name and leave PID empty
3. Raw dump is preferred
4. If the problem still occur, i will fix it ASAP

**Comment by MrWildanMD** [comment]
> I am passing the name and PID of the application, but it is returning empty. ![Screenshot_20231206-185315-1.png](https://private-user-images.githubusercontent.com/116834722/288546578-460bfc0b-6289-49c6-99c2-79976c4632cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MjMyMDksIm5iZiI6MTcwMTkyMjkwOSwicGF0aCI6Ii8xMTY4MzQ3MjIvMjg4NTQ2NTc4LTQ2MGJmYzBiLTYyODktNDljNi05OWMyLTc5OTc2YzQ2MzJjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QwNDIxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDE0Yzk1MjFmY2E4MTExNzE1MTJlZmYwNWQ0YzQ0Njg1YjAwNWRlODdjZDIyZTgyM2I4ZjVhZTkxNTFkMTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k4OcuuFaJvKvzNd_wJDdfZQQ036V_oPMYMuEINHnExc)
> 
> Can you help me?

and make sure ur android rooted

**Comment by Mr-Frey** [comment]
Hello, good morning. Yes, the device is rooted and I tried without the PID, but the result is the same, but I think the problem is that the apk doesn't have "libil2cpp.so", that must be it. I needed to dump another specific ".so", do you think there's any other way?

**Comment by MrWildanMD** [comment]
@Mr-Frey just specify the lib name in the LibName textfield...and if you're still facing same issue, lemme know, i'll try to fix it ASAP

**Comment by MrWildanMD** [comment]
because, if you leave the LibName textfield empty it will using the default value which is libil2cpp.so

**Comment by Mr-Frey** [comment]
Sorry for taking up your time @MrWildanMD. I was too stupid hehe. It worked perfectly, I hadn't realized that I had to pass the lib name in a field, I thought it would dump everything at once. Thanks for helping.
